baseURL = "https://codingezio.github.io/"
languageCode = "en-us"
title = "Hey there!"
theme = "yinyang"
enableEmoji = true
canonifyURLs = true
disableHugoGeneratorInject = true
paginate = 25
hasCJKLanguage = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
guessSyntax = true
tabWidth = 4

[author]
name = "Mensch"
homepage = "https://codingezio.github.io/"

[params]
mainSections = ["posts"]
headTitle = "Mensch"
[[params.socials]]
name = "About Me"
link = "https://codingezio.github.io"
[[params.socials]]
name = "Github"
link = "https://github.com/codingezio"
